### PR TITLE
Cleanup & white-label the email templates

### PR DESCRIPTION
**Pull request by maartenvn**
Use project name, color & logo inside the mail template.

## Screenshots

image
image

### CODE REVIEW

**Review by rijkvanzanten — APPROVED** [review]

**Comment by benhaynes** [comment]
Thanks @maartenvn — this is awesome! ❤️ 

One question: is the vertical alignment in that button really off? It seems optically high...

**Comment by maartenvn** [comment]
@benhaynes This is the box model:
image

According to the margins & padding, it should be centered

**Comment by rijkvanzanten** [comment]
@maartenvn what's the line height of that text?

**Comment by maartenvn** [comment]
@rijkvanzanten 
image

**Comment by rijkvanzanten** [comment]
The line-height is bigger than the available text line space in that box, pushing the text up a bit :)

**Comment by benhaynes** [comment]
Yeah, sometimes we'll need to "optically" align things. This probably looks off because of line-height, descenders, and its shorter height. Let's follow the same styling as other buttons in the system (eg: the login page):

Screen Shot 2020-11-02 at 10 32 45 AM

Including the height of 52px... bummer we can't use the v-button component in the emails! :)

**Pull request merged**
