### PR TITLE
Current route API preview

### PR DESCRIPTION
**Pull request by Kematia**
Hey! Did some work on the Preview API functionality, I'd love to get some feedback from the team...

The position of the modal activator is a placeholder, we could place it in the upcoming Export Data section in the sidebar, as @benhaynes suggested!

Couple screenshots...
image
image
image

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
I have a small concern about the 80/20-ness of this feature within the context of the sidebar on the browse page in regular use, but I think this is a superb addition to have under settings for administrator users 🤔 Thoughts on where this should live @benhaynes ?

**Comment by benhaynes** [comment]
First off, thank you @Kematia — this is awesome! 😍 

I agree with @rijkvanzanten — this is certainly useful, but a very power-user sort of feature. No matter where it goes, I think it needs to be admin-only.

If we all decide this is a bit too "heavy" for the Browse/Detail page, then I can certainly see it as a section of the Settings... perhaps as part of the dynamic API Reference Docs (as Rijk mentioned).

But I kinda like the idea of having this on Browse/Detail — perhaps as an admin-only link/button (eg: `Explore API Data`) within the upcoming "Data Export" sidebar component? Here's a quick mockup I made (second button opens up this modal):

Item Browse Sidebar Filter

**Comment by Kematia** [comment]
> First off, thank you @Kematia — this is awesome! 😍
> 
> I agree with @rijkvanzanten — this is certainly useful, but a very power-user sort of feature. No matter where it goes, I think it needs to be admin-only.
> 
> If we all decide this is a bit too "heavy" for the Browse/Detail page, then I can certainly see it as a section of the Settings... perhaps as part of the dynamic API Reference Docs (as Rijk mentioned).
> 
> But I kinda like the idea of having this on Browse/Detail — perhaps as an admin-only link/button (eg: `Explore API Data`) within the upcoming "Data Export" sidebar component? Here's a quick mockup I made (second button opens up this modal):
> 
> Item Browse Sidebar Filter
This is pretty much how I envisioned it, either admin-only or user-enabled

**Comment by Kematia** [comment]
As of now the api route to preview is discenred from the route, which I think is something I'd liked to keep for ease and speed of use, but it would be easy to expand the interface to accept a user-specified route/collection to preview.

This would unlock a more "explorer" like browsing and, something I'd really love, the ability to preview the collection you're building in the settings/data_model view.

**Comment by rijkvanzanten** [comment]
Thanks for the nice start @Kematia 🙂 We've moved the API testing IO into a dedicated section in the new docs module, so this PR has been included in and superseded by https://github.com/directus/next/pull/397 ❤️

**Pull request closed without merging**
