### PR TITLE
Color type line break under 600px

### LINKED ISSUE #974: Half width color interface is broken
Probably need to line break these to have it fit...

Screen Shot 2020-11-11 at 11 45 08 AM

### PR DESCRIPTION
**Pull request by Fusseldieb**
FIxes #974

Also just now seen that this was already assigned 😮

### CODE REVIEW

**Comment by Fusseldieb** [comment]
Still doesn't break in some cases, only in the mobile view. Closing for now.

**Comment by rijkvanzanten** [comment]
@Fusseldieb You can have it if you wanna pick it up! @Nitwel is heads down on #230 currently 🙂

**Comment by rijkvanzanten** [comment]
> media max-width applies to the whole screen 

Google around for "Container Queries" 😄 You'll find many devs running into your exact problem asking for a way to do media queries on a "component" instead of on the window. MS Edge just started a trial, so hopefully we can do it in the next couple years 💪

**Comment by rijkvanzanten** [comment]
@Fusseldieb Just FYI, interfaces get their configured width passed in as a prop. You can check for that `width` in case  you want to adjust the markup / styling on the configured size of the interface 🙂

**Comment by Fusseldieb** [comment]
> @Fusseldieb You can have it if you wanna pick it up! @Nitwel is heads down on #230 currently 🙂

Oh, that's nice @rijkvanzanten ! Would love to do it. 🙂

> Google around for "Container Queries" 😄 You'll find many devs running into your exact problem asking for a way to do media queries on a "component" instead of on the window. MS Edge just started a trial, so hopefully we can do it in the next couple years 💪

Yep, I found a lot about it after I've realized my mistake. 

> @Fusseldieb Just FYI, interfaces get their configured width passed in as a prop. You can check for that width in case you want to adjust the markup / styling on the configured size of the interface 🙂

Thanks for the heads-up. I will check for that.

One question that bugs me though: Why are the majority of elements styled with `grid`? Wouldn't flexbox be a wiser choice in some cases (like this)? It's relatively easy to make a flex element break to the line below when the size becomes too small.

In this project I've seen flex on some places and grid on others, I am now uncertain if I'm free to choose between the two or if I must follow a certain design choice. Would love to know more about to avoid unecessary invalid PRs.

Thanks in advance :)

**Comment by rijkvanzanten** [comment]
Both are used where appropriate! In this case, we don't want it to "just" wrap either, otherwise you end up with the dropdown for "blue" on a different line from "red" and "green".

Ideally, on half width, the dropdown for "type" (rgb/hsl/etc) should be full width, so you get

```
[ RGB                  ⌄ ]
[ R  ⌄ ] [ G  ⌄ ] [ B  ⌄ ]
```

**Comment by rijkvanzanten** [comment]
So in this case, it might actually be easier to use a 3 column grid with the first dropdown having span 3 which changes to 4 columns instead of trying to flex this 🙂

**Comment by Fusseldieb** [comment]
> So in this case, it might actually be easier to use a 3 column grid with the first dropdown having span 3 which changes to 4 columns instead of trying to flex this 🙂

Yep, that was what I was doing. I transformed the 4x1 grid to a 3x2 grid and made the color-type dropdown span across all 3 on top and the R, G, B on the bottom. Then I selectively added those rules (4x1 OR 3x2) with a media query (which is obviously wrong -  I had one of _those_ moments again).

> Both are used where appropriate! In this case, we don't want it to "just" wrap either, otherwise you end up with the dropdown for "blue" on a different line from "red" and "green".
>
>Ideally, on half width, the dropdown for "type" (rgb/hsl/etc) should be full width, so you get
>
> ```
> [ RGB                  ⌄ ]
> [ R  ⌄ ] [ G  ⌄ ] [ B  ⌄ ]
> ```

Thanks @rijkvanzanten. I was aware of that, but I was thinking on grouping the R, G and B elements together within a div/span and then enabling flex on the parent container. It could then break the type-selector and the 3 value selectors apart when needed. No fancy container queries needed.

What do you think?

**Comment by rijkvanzanten** [comment]
That'll work! Just keep in mind that there should be some margin between the two lines on smaller views, and that margin shouldn't affect the bottom spacing inside the dropdown when in "full" size. Unfortunately, flexbox-gap support isn't quite there yet https://caniuse.com/flexbox-gap, so that takes a bit of fiddling

**Comment by Fusseldieb** [comment]
> That'll work! Just keep in mind that there should be some margin between the two lines on smaller views, and that margin shouldn't affect the bottom spacing inside the dropdown when in "full" size.

Didn't quite catch that... Which margin are you talking about?

**Comment by rijkvanzanten** [comment]
There has to be some space in between here:

```
[ RGB                  ⌄ ]
             ↕
[ R  ⌄ ] [ G  ⌄ ] [ B  ⌄ ]
```

But we have to make sure it isn't there when it goes to one-line:

```
[ RGB   ⌄ ][ R  ⌄ ] [ G  ⌄ ] [ B  ⌄ ]
     ↕
```

**Comment by Fusseldieb** [comment]
> There has to be some space in between here:
> 
> ```
> [ RGB                  ⌄ ]
>              ↕
> [ R  ⌄ ] [ G  ⌄ ] [ B  ⌄ ]
> ```
> 
> But we have to make sure it isn't there when it goes to one-line:
> 
> ```
> [ RGB   ⌄ ][ R  ⌄ ] [ G  ⌄ ] [ B  ⌄ ]
>      ↕
> ```

Ohh, now it makes sense!
In my PR I have joined them together like:

image

What do you think? This or the spacing?

**Pull request closed without merging**
