### PR TITLE
Hide too many checkboxes

### PR DESCRIPTION
**Pull request by Nitwel**
This image shows how I implemented this but I'm up for a discussion on how we want to toggle this!
grafik

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Lets make the toggle like this:

CleanShot 2020-09-10 at 09 54 22

**Comment by rijkvanzanten** [comment]
@benhaynes Should we make this an option? I can imagine you might want to force it to show all of them at all times if you have 8–12 items (it cuts off at 7 now)

**Comment by Nitwel** [comment]
That looks better!

**Comment by benhaynes** [comment]
Yeah, I think it should be an option — could be a toggle or an INT of when to cut-off.

**Comment by Nitwel** [comment]
This is how it looks now:
grafik

And with custom options:
grafik

**Comment by Nitwel** [comment]
This should be ready for review now!

**Review by rijkvanzanten — APPROVED** [review]

**Pull request merged**
